services:
  alloy:
    image: grafana/alloy:v1.19.2
    container_name: alloy
    user: "0:0"
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log/host:ro
      - /mnt/user/appdata/alloy:/var/lib/alloy
      - ./config.alloy:/etc/alloy/config.alloy:ro
    mem_limit: 384m
    cpus: 0.35
