name: sjc-tool-portainer

services:
  portainer:
    image: portainer/portainer-ce:2.39.2
    container_name: portainer-ce
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "127.0.0.1:9444:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer/ce:/data
