name: phx-arm-immich

services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    restart: always
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    env_file:
      - path: /etc/phx-arm-compose/immich-database.env
        format: raw
    volumes:
      - /data/immich:/var/lib/postgresql/data

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2
    container_name: immich_machine_learning
    restart: always
    env_file:
      - path: /etc/phx-arm-compose/immich-machine-learning.env
        format: raw
    volumes:
      - model-cache:/cache

volumes:
  model-cache:
    external: true
    name: immich_model-cache
